---
- name: to install apache in my ubuntu machine
  become: yes
  hosts: ubuntu
  tasks:
    - name: i am going to update apt module
      apt:
        upgrade: yes
        update_cache: yes
    - name: i am going to install apache2
      apt:
        name=apache2 state=latest
    - name: i anm going to start my apache2
      service:
        name: apache2
        state: started